name: Test Action

on:
  pull_request:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
  contents: write

# Allow only one job per PR or branch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true # cancel jobs in progress

jobs:
  test:
    timeout-minutes: 180
    runs-on: ubuntu-latest
    name: Build, Test, Action

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - uses: actions/checkout@v3

      - run: mkdir dist/z
      - run: cd dist/z && echo '1' >> f1.png && cd ../.. && git status -s && git add dist/**/*.png && git diff --staged --name-only
      - run: cd dist/z && echo '2' >> f2.png && git status -s && git diff --staged --name-only
      - name: Local git-commit-pull-push-action 2
        uses: ./
        with:
          branch: ${{ github.head_ref }}
          commit_message: Update screenshots
          add_args: 'dist/**/*.png'
